### ISSUE TITLE
Add notion of refinement and poison into bitwise for division by zero

### ISSUE THREAD

**Issue by bollu** [bollu/ssa#12]
LLVM uses [poison](https://llvm.org/docs/LangRef.html#poison-values) to denote erroneous values. To perform the optimisation of replacing `p1 := Y = 0 ? X : X/Y` with `p2 := X/Y`, we need division by zero to return poison, define that poison is above concrete values in the value partial order, and that `p2 >= p1`.

**Comment by goens** [comment]
Closed by #25

**Comment by bollu** [comment]
Nice!

@goens one can write `fixes #25` in a pull request, which will auto close issue number 25 when the PR is merged.

**Comment by goens** [comment]
@bollu yeaah I did know that; to be honest I just forgot about this issue 🙈
